# Generated by Django 3.1.6 on 2021-02-14 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAndAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('professional', 'Professional'), ('skills', 'Skills'), ('foundation', 'Foundation'), ('atswa1', 'Atswa1'), ('atswa2', 'Atswa2'), ('atswa3', 'Atswa3')], default='professional', max_length=50)),
                ('slug', models.SlugField()),
                ('month', models.CharField(max_length=3)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
